/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupRouteImport } from './routes/group'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as WorkplaceRouteImport } from './routes/workplace'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiImageRouteImport } from './routes/api/image'
import { Route as ApiShopierCallbackRouteImport } from './routes/api/shopier-callback'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiWorkplaceRouteImport } from './routes/api/workplace'
import { Route as CIdRouteImport } from './routes/c.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupRoute = GroupRouteImport.update({
  id: '/group',
  path: '/group',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkplaceRoute = WorkplaceRouteImport.update({
  id: '/workplace',
  path: '/workplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageRoute = ApiImageRouteImport.update({
  id: '/api/image',
  path: '/api/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopierCallbackRoute = ApiShopierCallbackRouteImport.update({
  id: '/api/shopier-callback',
  path: '/api/shopier-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkplaceRoute = ApiWorkplaceRouteImport.update({
  id: '/api/workplace',
  path: '/api/workplace',
  getParentRoute: () => rootRouteImport,
} as any)
const CIdRoute = CIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/group': typeof GroupRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/workplace': typeof WorkplaceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/image': typeof ApiImageRoute
  '/api/shopier-callback': typeof ApiShopierCallbackRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/workplace': typeof ApiWorkplaceRoute
  '/c/$id': typeof CIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/group': typeof GroupRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/workplace': typeof WorkplaceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/image': typeof ApiImageRoute
  '/api/shopier-callback': typeof ApiShopierCallbackRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/workplace': typeof ApiWorkplaceRoute
  '/c/$id': typeof CIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/group': typeof GroupRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/workplace': typeof WorkplaceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/image': typeof ApiImageRoute
  '/api/shopier-callback': typeof ApiShopierCallbackRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/workplace': typeof ApiWorkplaceRoute
  '/c/$id': typeof CIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/group'
    | '/login'
    | '/shop'
    | '/workplace'
    | '/api/chat'
    | '/api/image'
    | '/api/shopier-callback'
    | '/api/tts'
    | '/api/workplace'
    | '/c/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/group'
    | '/login'
    | '/shop'
    | '/workplace'
    | '/api/chat'
    | '/api/image'
    | '/api/shopier-callback'
    | '/api/tts'
    | '/api/workplace'
    | '/c/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/group'
    | '/login'
    | '/shop'
    | '/workplace'
    | '/api/chat'
    | '/api/image'
    | '/api/shopier-callback'
    | '/api/tts'
    | '/api/workplace'
    | '/c/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupRoute: typeof GroupRoute
  LoginRoute: typeof LoginRoute
  ShopRoute: typeof ShopRoute
  WorkplaceRoute: typeof WorkplaceRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiImageRoute: typeof ApiImageRoute
  ApiShopierCallbackRoute: typeof ApiShopierCallbackRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiWorkplaceRoute: typeof ApiWorkplaceRoute
  CIdRoute: typeof CIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group': {
      id: '/group'
      path: '/group'
      fullPath: '/group'
      preLoaderRoute: typeof GroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workplace': {
      id: '/workplace'
      path: '/workplace'
      fullPath: '/workplace'
      preLoaderRoute: typeof WorkplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image': {
      id: '/api/image'
      path: '/api/image'
      fullPath: '/api/image'
      preLoaderRoute: typeof ApiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopier-callback': {
      id: '/api/shopier-callback'
      path: '/api/shopier-callback'
      fullPath: '/api/shopier-callback'
      preLoaderRoute: typeof ApiShopierCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workplace': {
      id: '/api/workplace'
      path: '/api/workplace'
      fullPath: '/api/workplace'
      preLoaderRoute: typeof ApiWorkplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$id': {
      id: '/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof CIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupRoute: GroupRoute,
  LoginRoute: LoginRoute,
  ShopRoute: ShopRoute,
  WorkplaceRoute: WorkplaceRoute,
  ApiChatRoute: ApiChatRoute,
  ApiImageRoute: ApiImageRoute,
  ApiShopierCallbackRoute: ApiShopierCallbackRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiWorkplaceRoute: ApiWorkplaceRoute,
  CIdRoute: CIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
